interface Currency {
  code: string;
  name: string;
  flag: string;
  showBadge?: boolean;
}

export const currencies: Currency[] = [
  {
    code: 'TRY',
    name: 'Türk Lirası',
    flag: '🇹🇷',
    showBadge: true,
  },
  {
    code: 'USD',
    name: 'Dolar',
    flag: '🇺🇸',
    showBadge: true,
  },
  {
    code: 'EUR',
    name: 'Euro',
    flag: '🇪🇺',
    showBadge: true,
  },
  {
    code: 'GBP',
    name: 'İngiliz Sterlini',
    flag: '🇬🇧',
    showBadge: true,
  },
  {
    code: 'CHF',
    name: 'İsviçre Frangı',
    flag: '🇨🇭',
    showBadge: true,
  },
  {
    code: 'CAD',
    name: 'Kanada Doları',
    flag: '🇨🇦',
    showBadge: true,
  },
  {
    code: 'RUB',
    name: 'Rus Rublesi',
    flag: '🇷🇺',
    showBadge: true,
  },
  {
    code: 'AED',
    name: 'BAE Dirhemi',
    flag: '🇦🇪',
    showBadge: true,
  },
  {
    code: 'AUD',
    name: 'Avustralya Doları',
    flag: '🇦🇺',
    showBadge: true,
  },
  {
    code: 'DKK',
    name: 'Danimarka Kronu',
    flag: '🇩🇰',
    showBadge: true,
  },
  {
    code: 'SEK',
    name: 'İsveç Kronu',
    flag: '🇸🇪',
    showBadge: true,
  },
  {
    code: 'NOK',
    name: 'Norveç Kronu',
    flag: '🇳🇴',
    showBadge: true,
  },
  {
    code: 'JPY',
    name: '100 Japon Yeni',
    flag: '🇯🇵',
    showBadge: true,
  },
  {
    code: 'KWD',
    name: 'Kuveyt Dinarı',
    flag: '🇰🇼',
    showBadge: true,
  },
  {
    code: 'ZAR',
    name: 'Güney Afrika Randı',
    flag: '🇿🇦',
    showBadge: true,
  },
  {
    code: 'BHD',
    name: 'Bahreyn Dinarı',
    flag: '🇧🇭',
    showBadge: true,
  },
  {
    code: 'LYD',
    name: 'Libya Dinarı',
    flag: '🇱🇾',
    showBadge: true,
  },
  {
    code: 'SAR',
    name: 'Suudi Arabistan Riyali',
    flag: '🇸🇦',
    showBadge: true,
  },
  {
    code: 'IQD',
    name: 'Irak Dinarı',
    flag: '🇮🇶',
    showBadge: true,
  },
  {
    code: 'ILS',
    name: 'İsrail Şekeli',
    flag: '🇮🇱',
    showBadge: true,
  },
  {
    code: 'IRR',
    name: 'İran Riyali',
    flag: '🇮🇷',
    showBadge: true,
  },
  {
    code: 'INR',
    name: 'Hindistan Rupisi',
    flag: '🇮🇳',
    showBadge: true,
  },
  {
    code: 'MXN',
    name: 'Meksika Pesosu',
    flag: '🇲🇽',
    showBadge: true,
  },
  {
    code: 'HUF',
    name: 'Macar Forinti',
    flag: '🇭🇺',
    showBadge: true,
  },
  {
    code: 'NZD',
    name: 'Yeni Zelanda Doları',
    flag: '🇳🇿',
    showBadge: true,
  },
  {
    code: 'BRL',
    name: 'Brezilya Reali',
    flag: '🇧🇷',
    showBadge: true,
  },
  {
    code: 'IDR',
    name: 'Endonezya Rupiahi',
    flag: '🇮🇩',
    showBadge: true,
  },
  {
    code: 'CZK',
    name: 'Çek Korunası',
    flag: '🇨🇿',
    showBadge: true,
  },
  {
    code: 'PLN',
    name: 'Polonya Zlotisi',
    flag: '🇵🇱',
    showBadge: true,
  },
  {
    code: 'RON',
    name: 'Romanya Leyi',
    flag: '🇷🇴',
    showBadge: true,
  },
  {
    code: 'CNY',
    name: 'Çin Yuanı',
    flag: '🇨🇳',
    showBadge: true,
  },
  {
    code: 'ARS',
    name: 'Arjantin Pesosu',
    flag: '🇦🇷',
    showBadge: true,
  },
  {
    code: 'CLP',
    name: 'Şili Pesosu',
    flag: '🇨🇱',
    showBadge: true,
  },
  {
    code: 'COP',
    name: 'Kolombiya Pesosu',
    flag: '🇨🇴',
    showBadge: true,
  },
  {
    code: 'CRC',
    name: 'Kostarika Kolonu',
    flag: '🇨🇷',
    showBadge: true,
  },
  {
    code: 'DZD',
    name: 'Cezayir Dinarı',
    flag: '🇩🇿',
    showBadge: true,
  },
  {
    code: 'EGP',
    name: 'Mısır Lirası',
    flag: '🇪🇬',
    showBadge: true,
  },
  {
    code: 'HKD',
    name: 'Hong Kong Doları',
    flag: '🇭🇰',
    showBadge: true,
  },
  {
    code: 'ISK',
    name: 'İzlanda Kronası',
    flag: '🇮🇸',
    showBadge: true,
  },
  {
    code: 'JOD',
    name: 'Ürdün Dinarı',
    flag: '🇯🇴',
    showBadge: true,
  },
  {
    code: 'KRW',
    name: 'Güney Kore Wonu',
    flag: '🇰🇷',
    showBadge: true,
  },
  {
    code: 'KZT',
    name: 'Kazak Tengesi',
    flag: '🇰🇿',
    showBadge: true,
  },
  {
    code: 'LBP',
    name: 'Lübnan Lirası',
    flag: '🇱🇧',
    showBadge: true,
  },
  {
    code: 'LKR',
    name: 'Sri Lanka Rupisi',
    flag: '🇱🇰',
    showBadge: true,
  },
  {
    code: 'MAD',
    name: 'Fas Dirhemi',
    flag: '🇲🇦',
    showBadge: true,
  },
  {
    code: 'MDL',
    name: 'Moldova Leusu',
    flag: '🇲🇩',
    showBadge: true,
  },
  {
    code: 'MKD',
    name: 'Makedon Dinarı',
    flag: '🇲🇰',
    showBadge: true,
  },
  {
    code: 'MYR',
    name: 'Malezya Ringgiti',
    flag: '🇲🇾',
    showBadge: true,
  },
  {
    code: 'OMR',
    name: 'Umman Riyali',
    flag: '🇴🇲',
    showBadge: true,
  },
  {
    code: 'PEN',
    name: 'Peru İnti',
    flag: '🇵🇪',
    showBadge: true,
  },
  {
    code: 'PHP',
    name: 'Filipinler Pesosu',
    flag: '🇵🇭',
    showBadge: true,
  },
  {
    code: 'PKR',
    name: 'Pakistan Rupisi',
    flag: '🇵🇰',
    showBadge: true,
  },
  {
    code: 'QAR',
    name: 'Katar Riyali',
    flag: '🇶🇦',
    showBadge: true,
  },
  {
    code: 'RSD',
    name: 'Sırbistan Dinarı',
    flag: '🇷🇸',
    showBadge: true,
  },
  {
    code: 'SGD',
    name: 'Singapur Doları',
    flag: '🇸🇬',
    showBadge: true,
  },
  {
    code: 'SYP',
    name: 'Suriye Lirası',
    flag: '🇸🇾',
    showBadge: true,
  },
  {
    code: 'THB',
    name: 'Tayland Bahtı',
    flag: '🇹🇭',
    showBadge: true,
  },
  {
    code: 'TWD',
    name: 'Yeni Tayvan Doları',
    flag: '🇹🇼',
    showBadge: true,
  },
  {
    code: 'UAH',
    name: 'Ukrayna Grivnası',
    flag: '🇺🇦',
    showBadge: true,
  },
  {
    code: 'UYU',
    name: 'Uruguay Pesosu',
    flag: '🇺🇾',
    showBadge: true,
  },
  {
    code: 'GEL',
    name: 'Gürcistan Larisi',
    flag: '🇬🇪',
    showBadge: true,
  },
  {
    code: 'TND',
    name: 'Tunus Dinarı',
    flag: '🇹🇳',
    showBadge: true,
  },
  {
    code: 'BGN',
    name: 'Bulgar Levası',
    flag: '🇧🇬',
    showBadge: true,
  },
];
